//! Procedural macros for tenferro extension crates.
//!
//! # Examples
//!
//! ```
//! use tenferro_extension_macros::ExtensionFamilyId;
//!
//! #[derive(ExtensionFamilyId)]
//! #[tenferro_extension(namespace = "my-crate", name = "fft", version = 1)]
//! struct FftOp;
//!
//! assert_eq!(FftOp::FAMILY_ID, "my-crate.fft.v1");
//! ```

use proc_macro::TokenStream;
use quote::quote;
use syn::parse::{Parse, ParseStream};
use syn::{parse_macro_input, DeriveInput, Expr, ExprLit, Lit, Token};

#[derive(Debug, Default)]
struct ExtensionArgs {
    namespace: Option<String>,
    name: Option<String>,
    version: Option<u64>,
}

impl Parse for ExtensionArgs {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let mut args = Self::default();
        while !input.is_empty() {
            let key: syn::Ident = input.parse()?;
            input.parse::<Token![=]>()?;
            let value: Expr = input.parse()?;
            match key.to_string().as_str() {
                "namespace" => args.namespace = Some(expect_string(value, "namespace")?),
                "name" => args.name = Some(expect_string(value, "name")?),
                "version" => args.version = Some(expect_u64(value, "version")?),
                other => {
                    return Err(syn::Error::new(
                        key.span(),
                        format!("unsupported tenferro_extension argument {other:?}"),
                    ));
                }
            }
            if input.is_empty() {
                break;
            }
            input.parse::<Token![,]>()?;
        }
        Ok(args)
    }
}

/// Derive an inherent `FAMILY_ID` constant for an extension payload type.
///
/// The required attribute is:
/// `#[tenferro_extension(namespace = "...", version = N)]`.
/// `name = "..."` is optional; when omitted, the Rust type name is converted
/// to snake_case.
#[proc_macro_derive(ExtensionFamilyId, attributes(tenferro_extension))]
pub fn derive_extension_family_id(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    match expand_extension_family_id(input) {
        Ok(tokens) => tokens.into(),
        Err(err) => err.to_compile_error().into(),
    }
}

fn expand_extension_family_id(input: DeriveInput) -> syn::Result<proc_macro2::TokenStream> {
    let mut parsed = None;
    for attr in &input.attrs {
        if attr.path().is_ident("tenferro_extension") {
            let args = attr.parse_args::<ExtensionArgs>()?;
            parsed = Some(args);
        }
    }
    let args = parsed.ok_or_else(|| {
        syn::Error::new_spanned(
            &input.ident,
            "missing #[tenferro_extension(namespace = \"...\", version = N)]",
        )
    })?;
    let namespace = args.namespace.ok_or_else(|| {
        syn::Error::new_spanned(&input.ident, "missing tenferro_extension namespace")
    })?;
    let version = args.version.ok_or_else(|| {
        syn::Error::new_spanned(&input.ident, "missing tenferro_extension version")
    })?;
    let name = args
        .name
        .unwrap_or_else(|| to_snake_case(&input.ident.to_string()));
    let family_id = format!("{namespace}.{name}.v{version}");
    let ident = input.ident;

    Ok(quote! {
        impl #ident {
            /// Stable extension family identifier generated by `ExtensionFamilyId`.
            pub const FAMILY_ID: &'static str = #family_id;
        }
    })
}

fn expect_string(value: Expr, field: &str) -> syn::Result<String> {
    match value {
        Expr::Lit(ExprLit {
            lit: Lit::Str(value),
            ..
        }) => Ok(value.value()),
        other => Err(syn::Error::new_spanned(
            other,
            format!("{field} must be a string literal"),
        )),
    }
}

fn expect_u64(value: Expr, field: &str) -> syn::Result<u64> {
    match value {
        Expr::Lit(ExprLit {
            lit: Lit::Int(value),
            ..
        }) => value.base10_parse(),
        other => Err(syn::Error::new_spanned(
            other,
            format!("{field} must be an integer literal"),
        )),
    }
}

fn to_snake_case(input: &str) -> String {
    let mut out = String::new();
    let mut prev_lower_or_digit = false;
    for ch in input.chars() {
        if ch.is_ascii_uppercase() {
            if prev_lower_or_digit {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
            prev_lower_or_digit = false;
        } else {
            prev_lower_or_digit = ch.is_ascii_lowercase() || ch.is_ascii_digit();
            out.push(ch);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::{expand_extension_family_id, to_snake_case, ExtensionArgs};
    use syn::DeriveInput;

    #[test]
    fn snake_case_type_name() {
        assert_eq!(to_snake_case("FftOp"), "fft_op");
        assert_eq!(to_snake_case("ScaleBy2"), "scale_by2");
    }

    #[test]
    fn derive_uses_snake_case_type_name_when_name_is_omitted() {
        let input: DeriveInput = syn::parse_quote! {
            #[tenferro_extension(namespace = "my-crate", version = 2)]
            struct FftPlanOp;
        };

        let tokens = expand_extension_family_id(input).expect("derive should expand");

        assert!(tokens.to_string().contains("\"my-crate.fft_plan_op.v2\""));
    }

    #[test]
    fn derive_reports_missing_attribute_fields() {
        let missing_attr: DeriveInput = syn::parse_quote! {
            struct MissingAttr;
        };
        assert!(expand_extension_family_id(missing_attr)
            .expect_err("missing attribute should fail")
            .to_string()
            .contains("missing #[tenferro_extension"));

        let missing_namespace: DeriveInput = syn::parse_quote! {
            #[tenferro_extension(version = 1)]
            struct MissingNamespace;
        };
        assert!(expand_extension_family_id(missing_namespace)
            .expect_err("missing namespace should fail")
            .to_string()
            .contains("missing tenferro_extension namespace"));

        let missing_version: DeriveInput = syn::parse_quote! {
            #[tenferro_extension(namespace = "my-crate")]
            struct MissingVersion;
        };
        assert!(expand_extension_family_id(missing_version)
            .expect_err("missing version should fail")
            .to_string()
            .contains("missing tenferro_extension version"));
    }

    #[test]
    fn derive_attribute_parser_rejects_unknown_and_wrong_typed_values() {
        assert!(syn::parse_str::<ExtensionArgs>(r#"unknown = "x""#)
            .expect_err("unknown argument should fail")
            .to_string()
            .contains("unsupported tenferro_extension argument"));
        assert!(syn::parse_str::<ExtensionArgs>("namespace = 1")
            .expect_err("namespace must be string")
            .to_string()
            .contains("namespace must be a string literal"));
        assert!(syn::parse_str::<ExtensionArgs>(r#"version = "1""#)
            .expect_err("version must be integer")
            .to_string()
            .contains("version must be an integer literal"));
    }
}
