# shellcheck shell=bash
#
# Run this repository's Python tooling on a uv-managed interpreter.
#
# The scripts need Python 3.11+ (`enum.StrEnum` in `scripts/ci/change_policy.py`,
# `tomllib` in the doc and API consistency checks) but every entry point invokes
# a bare `python3`. On macOS that is 3.9, so `check-pr-fast.sh` died inside
# `change_policy.py` before running a single check, while CI stayed green on its
# runner default. See #1606.
#
# uv is the premise: the interpreter always comes from `uv run`, pinned by
# `.python-version`, so a contributor and CI execute the same version rather
# than whatever each machine happens to ship.
#
# This fixes the NAME rather than the call sites. A script sources this file and
# keeps calling `python3`; a shim directory holding a `python3` that forwards to
# uv is prepended to PATH. Fixing PATH matters because the interpreter has to
# survive into CHILD processes: `scripts/ci/run_profile.py` runs its profile
# commands with `shell=True` and those commands spell `python3` too, so a
# per-call-site rewrite would fix the parent and leave every child behind. It
# also keeps the command strings that `scripts/ci/tests/test_run_profile.py`,
# `scripts/ci/tests/test_workflow_contracts.py` and
# `scripts/test-doc-consistency.py` pin for local/CI parity unchanged.
#
# `PYTHON` remains an escape hatch for someone who cannot install uv; it is
# accepted only if it is new enough.

TENFERRO_MIN_PYTHON="3.11"

tenferro_python_is_new_enough() {
  "$@" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)' \
    >/dev/null 2>&1
}

tenferro_pinned_python() {
  local root
  root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
  if [ -r "$root/.python-version" ]; then
    tr -d '[:space:]' <"$root/.python-version"
  else
    echo "3.12"
  fi
}

# Write `python3`/`python` shims that forward to "$@", and prepend them to PATH.
# The directory is stable per user, so repeated runs reuse it instead of
# leaking a fresh temporary directory each time.
tenferro_install_python_shim() {
  TENFERRO_PYTHON_SHIM_DIR="${TMPDIR:-/tmp}/tenferro-python-shim-$(id -u)"
  mkdir -p "$TENFERRO_PYTHON_SHIM_DIR" || return 1
  {
    echo '#!/usr/bin/env bash'
    echo '# Generated by scripts/lib/python.sh (issue #1606). Safe to delete.'
    printf 'exec'
    printf ' %q' "$@"
    echo ' "$@"'
  } >"$TENFERRO_PYTHON_SHIM_DIR/python3" || return 1
  chmod +x "$TENFERRO_PYTHON_SHIM_DIR/python3" || return 1
  # `python` too: leaving it absent or pointing at a 2.x binary while `python3`
  # is modern is its own trap.
  cp "$TENFERRO_PYTHON_SHIM_DIR/python3" "$TENFERRO_PYTHON_SHIM_DIR/python" || return 1
  PATH="$TENFERRO_PYTHON_SHIM_DIR:$PATH"
  export PATH TENFERRO_PYTHON_SHIM_DIR
}

tenferro_ensure_python() {
  if [ -n "${TENFERRO_PYTHON_READY:-}" ]; then
    return 0
  fi

  if [ -n "${PYTHON:-}" ]; then
    # shellcheck disable=SC2206
    local override=($PYTHON)
    if ! tenferro_python_is_new_enough "${override[@]}"; then
      echo "PYTHON=$PYTHON is older than $TENFERRO_MIN_PYTHON" >&2
      return 1
    fi
    tenferro_install_python_shim "${override[@]}" || return 1
    export TENFERRO_PYTHON_READY=1
    return 0
  fi

  if ! command -v uv >/dev/null 2>&1; then
    {
      echo "uv is required to run this repository's Python tooling."
      echo "Install it from https://docs.astral.sh/uv/ — it fetches and caches"
      echo "the pinned interpreter from .python-version for you."
      echo "To use an existing interpreter instead, set PYTHON to a"
      echo "$TENFERRO_MIN_PYTHON+ one."
    } >&2
    return 1
  fi

  # `--no-project` keeps uv from trying to resolve a project that does not
  # exist here; the managed interpreter is downloaded once and cached.
  local pinned
  pinned="$(tenferro_pinned_python)"
  local uv_python=(uv run --no-project --python "$pinned" python)
  if ! tenferro_python_is_new_enough "${uv_python[@]}"; then
    echo "uv could not provide a Python $TENFERRO_MIN_PYTHON+ interpreter (pinned: $pinned)" >&2
    return 1
  fi
  tenferro_install_python_shim "${uv_python[@]}" || return 1
  export TENFERRO_PYTHON_READY=1
}

tenferro_ensure_python || exit 1
