#!/usr/bin/env bash
set -euo pipefail

# shellcheck source=scripts/lib/python.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)/lib/python.sh"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
OUT_DIR="${1:-$ROOT_DIR/target/docs-site}"
API_DIR="$OUT_DIR/api"
DOC_ROOT="$ROOT_DIR/target/doc"
API_INDEX_MD="$ROOT_DIR/docs/api/index.md"

rm -rf "$OUT_DIR"
mkdir -p "$API_DIR"

render_overview_html() {
  if [[ -f "$API_INDEX_MD" ]]; then
    if command -v pandoc >/dev/null 2>&1; then
      pandoc "$API_INDEX_MD" -f gfm -t html5
      return
    fi
    printf '<pre>'
    sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' "$API_INDEX_MD"
    printf '</pre>\n'
    return
  fi

  py - "$ROOT_DIR" <<'PY'
import html
import json
import pathlib
import subprocess
import sys

root = pathlib.Path(sys.argv[1])
metadata = subprocess.run(
    ["cargo", "metadata", "--no-deps", "--format-version", "1"],
    check=True,
    cwd=root,
    stdout=subprocess.PIPE,
    text=True,
)
workspace = json.loads(metadata.stdout)
members = set(workspace["workspace_members"])
print("<h1>Workspace API</h1>")
print("<p>Autogenerated crate inventory for this workspace.</p>")
print("<ul>")
for package_info in workspace["packages"]:
    if package_info["id"] not in members:
        continue
    lib_targets = [
        target
        for target in package_info["targets"]
        if "lib" in target["kind"] or "proc-macro" in target["kind"]
    ]
    if not lib_targets:
        continue
    package = package_info["name"]
    doc_dir = lib_targets[0]["name"]
    print(f'<li><a href="{html.escape(doc_dir)}/index.html">{html.escape(package)}</a></li>')
print("</ul>")
PY
}

render_crate_inventory_html() {
  py - "$ROOT_DIR" <<'PY'
import html
import json
import pathlib
import subprocess
import sys

root = pathlib.Path(sys.argv[1])
metadata = subprocess.run(
    ["cargo", "metadata", "--no-deps", "--format-version", "1"],
    check=True,
    cwd=root,
    stdout=subprocess.PIPE,
    text=True,
)
workspace = json.loads(metadata.stdout)
members = set(workspace["workspace_members"])

print("<h2>Workspace Crates</h2>")
print("<ul>")
for package_info in workspace["packages"]:
    if package_info["id"] not in members:
        continue
    lib_targets = [
        target
        for target in package_info["targets"]
        if "lib" in target["kind"] or "proc-macro" in target["kind"]
    ]
    if not lib_targets:
        continue
    member = str(pathlib.Path(package_info["manifest_path"]).parent.relative_to(root))
    package = package_info["name"]
    doc_dir = lib_targets[0]["name"]
    print(
        f'<li><a href="{html.escape(doc_dir)}/index.html">{html.escape(package)}</a>'
        f' <code>{html.escape(member)}</code></li>'
    )
print("</ul>")
PY
}

echo "[1/9] Checking user-facing snippets"
py "$ROOT_DIR/scripts/check-doc-snippets.py" --root-dir "$ROOT_DIR" --check
py "$ROOT_DIR/scripts/check-guide-dependency-snippets.py" --root-dir "$ROOT_DIR"

echo "[2/9] Building rustdoc"
rm -rf "$DOC_ROOT"
cargo doc --workspace --no-deps

echo "[3/9] Copying rustdoc output"
cp -a "$DOC_ROOT/." "$API_DIR/"

echo "[4/9] Generating optional dependency graph"
if [[ -x "$ROOT_DIR/scripts/gen_dep_graph.py" || -f "$ROOT_DIR/scripts/gen_dep_graph.py" ]]; then
  if command -v dot >/dev/null 2>&1; then
    py "$ROOT_DIR/scripts/gen_dep_graph.py" --root-dir "$ROOT_DIR" --format svg \
      --output "$API_DIR/dep_graph.svg"
  else
    echo "  Warning: graphviz (dot) not found; dependency graph skipped."
    if [[ "${CI:-}" == "true" ]]; then
      echo "  graphviz is required in CI to render the dependency graph."
      exit 1
    fi
  fi
else
  echo "  No scripts/gen_dep_graph.py found; skipping dependency graph."
fi

echo "[5/9] Rendering API landing page"
OVERVIEW_HTML="$(render_overview_html)"
CRATE_INVENTORY_HTML="$(render_crate_inventory_html)"
{
  cat <<'HEADER'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Workspace API docs</title>
    <style>
      body { font-family: "IBM Plex Sans", "Segoe UI", sans-serif; margin: 2rem auto; max-width: 56rem; padding: 0 1rem; color: #14231f; }
      h1 { margin-bottom: 0.5rem; }
      h2 { margin-top: 2rem; color: #2e3d38; }
      p { color: #3a4a45; line-height: 1.6; }
      ul { line-height: 1.8; }
      a { color: #0c7a5a; text-decoration: none; }
      a:hover { text-decoration: underline; }
      code { font-family: "IBM Plex Mono", "SFMono-Regular", monospace; }
      pre { background: #f4f7f5; padding: 1rem; border-radius: 6px; overflow-x: auto; }
      .inventory code { margin-left: 0.4rem; color: #426058; }
    </style>
  </head>
  <body>
HEADER
  printf '%s\n' "$OVERVIEW_HTML"
  printf '<section class="inventory">\n%s\n</section>\n' "$CRATE_INVENTORY_HTML"
  cat <<'FOOTER'
  </body>
</html>
FOOTER
} >"$API_DIR/index.html"

echo "[6/9] Rendering design docs if configured"
if [[ -f "$ROOT_DIR/docs/_quarto.yml" ]]; then
  if command -v quarto >/dev/null 2>&1; then
    quarto render "$ROOT_DIR/docs"
  else
    echo "  Warning: quarto not found; design docs site skipped."
    if [[ "${CI:-}" == "true" ]]; then
      echo "  quarto is required in CI to render design docs."
      exit 1
    fi
  fi
else
  echo "  No docs/_quarto.yml found; skipping design docs render."
fi

echo "[7/9] Checking rendered operation surface references"
py "$ROOT_DIR/scripts/check-operation-categories.py" --fail-on-findings --include-rendered

echo "[8/9] Verifying docs site links and API inventory"
py "$ROOT_DIR/scripts/check-docs-site.py" --root-dir "$ROOT_DIR" --site-index "$API_DIR/index.html"

echo "[9/9] Verifying site top page"
REPO_TITLE="$(basename "$ROOT_DIR")"
if [[ -f "$OUT_DIR/index.html" ]]; then
  echo "  Using Quarto-rendered site index."
else
  echo "  Quarto index missing; generating fallback top page."
  cat >"$OUT_DIR/index.html" <<EOF
<!doctype html>
<html lang="en">
  <head><meta charset="utf-8" /><title>${REPO_TITLE} docs</title></head>
  <body>
    <main>
      <h1>${REPO_TITLE} Documentation</h1>
      <p>Build the full documentation with Quarto to see the user guide landing page.</p>
      <p><a href="./api/index.html">API Reference</a></p>
    </main>
  </body>
</html>
EOF
fi

echo "Done: $OUT_DIR"
