#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
OUT_DIR="${1:-$ROOT_DIR/target/docs-site}"
DESIGN_DIR="$OUT_DIR/design"
API_DIR="$OUT_DIR/api"

rm -rf "$OUT_DIR"
mkdir -p "$DESIGN_DIR" "$API_DIR"

echo "[1/5] Building rustdoc"
rm -rf "$ROOT_DIR/target/doc"
cargo doc --workspace --no-deps

echo "[2/5] Copying rustdoc output"
cp -a "$ROOT_DIR/target/doc/." "$API_DIR/"

echo "[3/5] Generating dependency graph and API index"
DEP_SVG=""
if command -v dot >/dev/null 2>&1; then
  python3 "$ROOT_DIR/scripts/gen_dep_graph.py" --root-dir "$ROOT_DIR" \
    | dot -Tsvg > "$API_DIR/dep_graph.svg"
  DEP_SVG=$(cat "$API_DIR/dep_graph.svg")
else
  echo "  Warning: graphviz (dot) not found; dependency graph SVG skipped."
  if [ "${CI:-}" = "true" ]; then
    echo "  graphviz is required in CI to generate the dependency graph."
    exit 1
  fi
fi

{
  cat <<'HEADER'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>tenferro-rs API docs</title>
    <style>
      body { font-family: "IBM Plex Sans", "Segoe UI", sans-serif; margin: 2rem auto; max-width: 56rem; padding: 0 1rem; }
      h1 { margin-bottom: 0.5rem; }
      h2 { margin-top: 2rem; color: #2e3d38; }
      p { color: #3a4a45; }
      ul { line-height: 1.8; }
      a { color: #0c7a5a; text-decoration: none; }
      a:hover { text-decoration: underline; }
      code { font-family: "IBM Plex Mono", "SFMono-Regular", monospace; }
      .dep-graph { margin: 1.5rem 0; text-align: center; }
      .dep-graph svg { max-width: 100%; height: auto; }
    </style>
  </head>
  <body>
    <h1>tenferro-rs API reference</h1>
    <p>Workspace crate documentation generated by <code>cargo doc</code>.</p>
HEADER

  if [ -n "$DEP_SVG" ]; then
    cat <<'GRAPH_HEADER'
    <h2>Dependency graph</h2>
    <p>Click a node to open the crate documentation.</p>
    <div class="dep-graph">
GRAPH_HEADER
    echo "$DEP_SVG"
    echo '    </div>'
  fi

  cat <<'CRATE_HEADER'
    <h2>Crates</h2>
    <ul>
CRATE_HEADER
  while IFS= read -r crate_dir; do
    if [ -f "$API_DIR/$crate_dir/index.html" ]; then
      printf '      <li><a href="./%s/index.html">%s</a></li>\n' "$crate_dir" "$crate_dir"
    fi
  done < <(find "$API_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)
  cat <<'FOOTER'
    </ul>
  </body>
</html>
FOOTER
} >"$API_DIR/index.html"

echo "[4/5] Converting docs/design markdown to HTML"
for md in "$ROOT_DIR"/docs/design/*.md; do
  base="$(basename "$md" .md)"
  html="$DESIGN_DIR/$base.html"

  if command -v pandoc >/dev/null 2>&1; then
    pandoc "$md" -f gfm -t html5 -o "$html" --standalone
  else
    if [ "${CI:-}" = "true" ]; then
      echo "pandoc is required in CI to render docs/design/*.md as HTML."
      exit 1
    fi
    {
      printf '<!doctype html><html><head><meta charset="utf-8"><title>%s</title></head><body><pre>\n' "$base"
      sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' "$md"
      printf '\n</pre></body></html>\n'
    } >"$html"
  fi
done

echo "[5/5] Copying site top page"
cp "$ROOT_DIR/docs/site_index.html" "$OUT_DIR/index.html"

echo "Done: $OUT_DIR"
